changelog:
  exclude:
    labels: []
  categories:
    - title: "✨ Exciting New Features"
      labels:
        - "🌟 feature"
    - title: "🧩 Pieces"
      labels:
        - "🔌 pieces"
    - title: "🛠️ Piece Framework"
      labels:
        - "🛠️ piece-framework"
    - title: "🐞 Bug Fixes"
      labels:
        - "🐛 bug"
    - title: "🎨 Enhancements & Polish"
      labels:
        - "⭐ enhancement"
    - title: "📚 Documentation"
      labels:
        - "📚 documentation"
    - title: "Other Changes"
      labels:
        - "*"
