services:
  activepieces:
    image: ghcr.io/activepieces/activepieces:0.34.11
    container_name: activepieces
    restart: unless-stopped
    ports:
      - '443:4022'  # Maps host port 443 (HTTPS) to container port 4022
    environment:
      - DATABASE_URL=postgres://${AP_POSTGRES_USERNAME}:${AP_POSTGRES_PASSWORD}@postgres:5432/${AP_POSTGRES_DATABASE}
    depends_on:
      - postgres
      - redis
    networks:
      - activepieces
      - dokploy-network
    volumes:
      - ./your-ssl-certificate:/etc/ssl/certs
      - ./your-ssl-key:/etc/ssl/private

  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=${AP_POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${AP_POSTGRES_USERNAME}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - activepieces
      - dokploy-network  # Adding external network here

  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - 'redis_data:/data'
    networks:
      - activepieces
      - dokploy-network  # Adding external network here

volumes:
  postgres_data:
  redis_data:

networks:
  activepieces:
  dokploy-network:
    external: true  # Declaring external network
