version: '3.0'
services:
  activepieces:
    image: ghcr.io/activepieces/activepieces:0.34.11
    container_name: activepieces
    restart: unless-stopped
    ports:
      - '443:80'  # Maps host port 443 to container port 80 for HTTPS
    environment:
      # DATABASE_URL constructed using env variables
      - DATABASE_URL=postgres://${AP_POSTGRES_USERNAME}:${AP_POSTGRES_PASSWORD}@postgres:5432/${AP_POSTGRES_DATABASE}
    depends_on:
      - postgres
      - redis
    networks:
      - activepieces
    volumes:
      - ./your-ssl-certificate:/etc/ssl/certs  # Mount your SSL certificate
      - ./your-ssl-key:/etc/ssl/private  # Mount your SSL private key

  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=${AP_POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${AP_POSTGRES_USERNAME}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - activepieces

  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - 'redis_data:/data'
    networks:
      - activepieces

volumes:
  postgres_data:
  redis_data:

networks:
  activepieces:
